---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coil-controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coil.cybozu.com
  resources:
  - addressblocks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coil.cybozu.com
  resources:
  - addresspools
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coil.cybozu.com
  resources:
  - blockrequests
  - egresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coil.cybozu.com
  resources:
  - blockrequests/status
  - egresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - get
  - list
  - patch
  - update
  - watch
