apiVersion: v1
kind: Namespace
metadata:
  name: internet
---
apiVersion: coil.cybozu.com/v2
kind: Egress
metadata:
  name: egress-sport-auto-nft
  namespace: internet
spec:
  replicas: 2
  destinations:
  - 0.0.0.0/0
  - ::/0
  fouSourcePortAuto: true
  enableNFT: true
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: coil-control-plane
      tolerations:
      - effect: NoSchedule
        operator: Exists
      containers:
      - name: egress
