apiVersion: v1
kind: Pod
metadata:
  name: nat-client-cluster-networks
  namespace: default
  annotations:
    egress.coil.cybozu.com/internet: egress-cluster-networks
spec:
  tolerations:
  - key: test
    operator: Exists
  nodeSelector:
    test: coil
    kubernetes.io/hostname: coil-worker
  containers:
  - name: ubuntu
    image: ghcr.io/cybozu/ubuntu-debug:22.04
    command: ["pause"]
